import { useState, useEffect } from 'react';
import { api } from '../../api';

export const AIInsights: React.FC = () => {
  const [trends, setTrends] = useState<any>(null);
  const [report, setReport] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchAIData = async () => {
      try {
        const [trendsRes, reportRes] = await Promise.all([
          api.get('/risks/ai/trends'),
          api.get('/risks/ai/report'),
        ]);
        setTrends(trendsRes.data);
        setReport(reportRes.data.report);
      } catch (err) {
        console.error('AI fetch error:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchAIData();
  }, []);

  if (loading) {
    return (
      <div className="card flex items-center justify-center h-64">
        <svg className="animate-spin h-8 w-8 text-indigo-500" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
        </svg>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="card">
        <div className="flex items-center gap-3 mb-4">
          <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center">
            <span className="text-xl">🤖</span>
          </div>
          <div>
            <h2 className="text-lg font-black text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-400">
              AI Executive Report
            </h2>
            <p className="text-xs text-slate-400">Generated by Gemini AI</p>
          </div>
        </div>
        <div className="p-4 rounded-xl bg-slate-800/30 border border-slate-700/30">
          <p className="text-sm text-slate-300 leading-relaxed whitespace-pre-line">
            {report || 'No report available'}
          </p>
        </div>
      </div>

      {trends && (
        <div className="card">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-indigo-600 to-purple-600 flex items-center justify-center">
              <span className="text-xl">📈</span>
            </div>
            <div>
              <h2 className="text-lg font-black text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">
                AI Trend Analysis
              </h2>
              <p className="text-xs text-slate-400">Predictive insights</p>
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-2">
            <div className="p-4 rounded-xl bg-gradient-to-br from-indigo-500/10 to-purple-500/10 border border-indigo-500/30">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">
                Overall Trend
              </p>
              <p className="text-lg font-black text-indigo-300">
                {trends.trend || 'Stable'}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-gradient-to-br from-red-500/10 to-pink-500/10 border border-red-500/30">
              <p className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-2">
                Vulnerable Areas
              </p>
              <div className="space-y-1">
                {trends.vulnerableAreas?.map((area: string, i: number) => (
                  <p key={i} className="text-sm font-bold text-red-300">
                    • {area}
                  </p>
                ))}
              </div>
            </div>
          </div>

          <div className="mt-4 p-4 rounded-xl bg-slate-800/30 border border-slate-700/30">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
              AI Predictions
            </p>
            <div className="space-y-2">
              {trends.predictions?.map((pred: string, i: number) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="text-purple-400 mt-1">▸</span>
                  <p className="text-sm text-slate-300">{pred}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-4 p-4 rounded-xl bg-gradient-to-br from-emerald-500/10 to-teal-500/10 border border-emerald-500/30">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-3">
              AI Recommendations
            </p>
            <div className="space-y-2">
              {trends.recommendations?.map((rec: string, i: number) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="text-emerald-400 mt-1">✓</span>
                  <p className="text-sm text-slate-300">{rec}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
